### ISSUE TITLE
Indentation by spaces instead of tabs

### ISSUE THREAD

**Issue by oanhnn** [laravel-presets/tailwindcss#2]
Default Laravel using indentation by 4 spaces, but this preset using tab.
So that, after apply this preset, users (majority) MUST change indentation by hand or IDE.
I think this preset SHOULD use indentation by 4 spaces.

**Comment by innocenzi** [comment]
I'm a tab kind of guy myself, but I'll keep it the same as Laravel's default, for consistency's sake. Thanks for pointing it out!

**Comment by kielabokkie** [comment]
@innocenzi Just letting you know that the tabs seem to have returned in the latest version 😉

**Comment by innocenzi** [comment]
Ah, thanks for letting me know. The new handler is supposed to detect indentation and reuse it, so I'll try to see what's wrong tonight.

**Comment by innocenzi** [comment]
@kielabokkie do you have more information about the issue you got? It works as expected for me. No tabs, the indentation is properly detected and reused. 

![](https://i.imgur.com/kQJMoRq.png)

**Comment by kielabokkie** [comment]
@innocenzi Sorry, I wasn't very clear 😄

I noticed tabs are in the following files:
* `tailwind.config.js`
* `postcss.config.js` 
* `webpack.mix.js`
* `welcome.blade.php`

**Comment by innocenzi** [comment]
Oh, that's right. My bad. I'll update that along with the prettier rules. Thanks again!
